name: Get Events

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:
    # Allow manual triggering
    inputs:
      specific_event_slug:
        description: 'Slug of a specific event to process (for past events)'
        required: false

jobs:
  get-events:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Execute python
        env:
          PRETIX_URL: ${{ secrets.PRETIX_URL || 'https://events.helsec.fi' }}
          ORGANIZER_SLUG: ${{ secrets.ORGANIZER_SLUG || 'test' }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          SPECIFIC_EVENT_SLUG: ${{ github.event.inputs.specific_event_slug }}
          EVENTS_DIRECTORY: content/events
        run: |
          python get_events.py
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update events!"
          commit_user_name: HelSec-bot
          commit_user_email: contact@helsec.fi
          commit_author: HelSec-Bot <contact@helsec.fi>

